name: Trigger Jenkins Job

on:
  push:
    branches:
      - dev
      - staging
      - main
  workflow_dispatch: # Permite ejecución manual

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener la rama y construir URL de Jenkins
      - name: Get branch name and build Jenkins URL
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          JENKINS_URL="https://automation.prms.cgiar.org/job/prms-bilateral-${BRANCH_NAME}/build"
          echo "Jenkins job URL for the branch $BRANCH_NAME is: $JENKINS_URL"
          echo "JENKINS_URL=${JENKINS_URL}" >> $GITHUB_ENV

      # Paso 2: Ejecutar curl para disparar el job
      - name: Trigger Jenkins Job
        run: |
          curl -X POST ${{ env.JENKINS_URL }} --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
        env:
          JENKINS_URL: ${{ env.JENKINS_URL }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
